name: environment demo

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ vars.MY_VAR }}
  deployment:
    environment: DEV
    runs-on: windows-latest
    steps:
      - run: echo ${{ vars.MY_VAR }}
